import type { ProjectConfig } from "./projectConfig.ts";
import type { CommentState } from "./states.ts";

export type Id = string; // ULID-like, generated by the companion

// ---------- Projects ----------

export interface CheckoutStatus {
  alias: string;
  path: string | null; // null = not mapped yet
  ok: boolean;
  /** Human-readable reason when !ok, e.g. "Ordner fehlt", "Kein Git-Checkout", "Nicht lesbar". */
  problem?: string;
  headCommit?: string;
  branch?: string;
  hasUncommittedChanges?: boolean;
}

export interface KanConnectionStatus {
  baseUrl: string;
  tokenConfigured: boolean;
  /** Result of the last check against the Kan API; undefined = not checked yet. */
  tokenValid?: boolean;
  targetValid?: boolean;
  problem?: string;
}

/** What the extension sees for a project: shareable config + local-only status. */
export interface ProjectView {
  config: ProjectConfig;
  checkouts: CheckoutStatus[];
  kan: KanConnectionStatus;
  /** True when every alias is mapped to a readable checkout and Kan token + target are valid. */
  readyForProcessing: boolean;
}

// ---------- Capture ----------

export type MarkKind = "element" | "point" | "page";

export interface Rect {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface Point {
  x: number;
  y: number;
}

/** Context captured by the extension at the moment of commenting. */
export interface CaptureContext {
  url: string;
  pageTitle: string;
  viewport: { width: number; height: number; devicePixelRatio: number };
  scroll: { x: number; y: number };
  /** Visible text of the selected element, trimmed and capped (element marks only). */
  elementText?: string;
  /** Short descriptive hint, e.g. `button.primary "Speichern"`; context only, not used to re-find elements. */
  elementDescription?: string;
  /** Extra page text the user explicitly added (design: "weiterer Seiteninhalt nur gezielt"). */
  extraContext?: string;
}

/**
 * Screenshot as approved by the user. All coordinates are in pixels of the FINAL (cropped) image.
 * The final PNG already has the marker drawn into it.
 */
export interface ScreenshotMeta {
  width: number;
  height: number;
  /** Size of the uncropped capture (captureVisibleTab output, device pixels). */
  originalWidth: number;
  originalHeight: number;
  /** Crop rectangle in original-image pixels. Equal to the full image when not cropped. */
  crop: Rect;
  /** Marker in final-image pixels (element + point marks). */
  marker?: Point;
  /** Element outline in final-image pixels (element marks), clipped to the crop. */
  elementBox?: Rect;
}

// ---------- Codex analysis (structured turn output, validated by the companion) ----------

export interface CodeFinding {
  repository: string; // alias
  path: string; // relative to checkout root
  lineStart?: number;
  lineEnd?: number;
  note: string; // why this location is relevant
}

export interface OpenQuestion {
  id: string;
  text: string;
  answer?: string;
  answeredAt?: string;
}

export interface DuplicateCandidate {
  cardPublicId: string;
  title: string;
  url: string;
  reason: string;
}

export interface TicketDraft {
  title: string;
  desiredChange: string;
  /** Explicitly open details (e.g. "Ein genauer Zielabstand wurde nicht festgelegt."). */
  openPoints: string[];
  /** Presumed solutions; rendered under "Umsetzungsideen (Vermutung)". */
  implementationIdeas: string[];
}

export interface CheckoutSnapshot {
  alias: string;
  headCommit: string;
  branch?: string;
  hasUncommittedChanges: boolean;
}

export interface CommentAnalysis {
  revision: number; // the input revision this analysis belongs to
  ticket: TicketDraft;
  findings: CodeFinding[];
  checkouts: CheckoutSnapshot[];
  analyzedAt: string;
}

// ---------- Decisions ----------

export interface MergeProposal {
  id: Id;
  reviewId: Id;
  commentIds: Id[];
  reason: string;
  status: "open" | "accepted" | "rejected";
}

export type PendingDecision =
  | { kind: "duplicate"; candidates: DuplicateCandidate[] }
  | { kind: "merge"; proposalId: Id };

export type DecisionInput =
  | { kind: "duplicate"; action: "append"; cardPublicId: string }
  | { kind: "duplicate"; action: "create_new" }
  | { kind: "merge"; proposalId: Id; action: "accept" | "reject" };

// ---------- Publication ----------

export type PublicationKind = "create_card" | "add_comment" | "upload_attachment";
export type PublicationOpState = "intended" | "sent" | "confirmed" | "failed" | "unclear";

export interface PublicationOp {
  id: Id;
  commentId: Id; // primary comment (for merged tickets: the group's primary)
  revision: number;
  kind: PublicationKind;
  /** Stable reference embedded in the published content, e.g. "wr-01J9…". Used for reconciliation. */
  reference: string;
  state: PublicationOpState;
  cardPublicId?: string;
  externalId?: string; // comment/attachment publicId
  error?: string;
  createdAt: string;
  updatedAt: string;
}

export interface TicketLink {
  cardPublicId: string;
  url: string;
  title: string;
  /** "created" = new card; "appended" = feedback added as comment on an existing card. */
  mode: "created" | "appended";
  attachmentUploaded: boolean;
}

// ---------- Review & comments ----------

export interface Comment {
  id: Id;
  reviewId: Id;
  revision: number;
  text: string;
  markKind: MarkKind;
  context: CaptureContext;
  screenshot?: ScreenshotMeta; // image served at GET /v1/comments/:id/image
  state: CommentState;
  /** Human-readable status detail, e.g. failure reason or what the next step is. */
  stateDetail?: string;
  questions: OpenQuestion[];
  pendingDecision?: PendingDecision;
  /** Set when the user accepted a merge: all comments of the group share one ticket. */
  mergeGroupId?: Id;
  analysis?: CommentAnalysis;
  ticket?: TicketLink;
  createdAt: string;
  updatedAt: string;
}

export interface Review {
  id: Id;
  projectId: string;
  title: string;
  createdAt: string;
  updatedAt: string;
  /** Codex thread id for the shared review session; resumption never depends on it alone. */
  codexThreadId?: string;
}

export interface ReviewSummary extends Review {
  counts: Partial<Record<CommentState, number>>;
}

export interface ReviewDetail extends Review {
  comments: Comment[];
  mergeProposals: MergeProposal[];
  processing: boolean;
}
